-- SELECTING ALL FROM TABLE
SELECT * FROM pizza_sales;

-- TOTAL REVENUE : SUM OF ALL THE TOTAL PRICE OF ALL THE PIZZA ORDERS
SELECT SUM(total_price) AS TOTAL_REVENUE FROM pizza_sales   

-- AVERAGE ORDER VALUE : THE AVAERAGE AMOUNT SPENT PER ORDER, CALCULATED BY DIVIDING THE TOTAL REVENUE BY THE TOTAL NUMBER OF ORDERS
SELECT SUM(total_price) / COUNT(DISTINCT(order_id)) AS AVG_ORDER_VALUE FROM pizza_sales

-- TOTAL PIZZA'S SOLD : THE SUM OF THE QUANITITIES OF THE ALL PIZZAS SOLD
SELECT SUM(QUANTITY) AS PIZZA_SOLD FROM pizza_sales

--TOTAL ORDERS : TOTAL NUMBER OF ORDERS PLACED
SELECT COUNT(DISTINCT(order_id)) AS TOTAL_ORDERS FROM pizza_sales

--AVERAGE PIZZAS PER ORDER : THE AVERAGE NUMBER OF PIZZAS SOLD PER ORDER , CALCULATED BY DIVIDING THE TOTAL NUMBER OF PIZZAS SOLD BY THE TOTAL NUMBER OF ORDERS
 SELECT CAST(CAST(SUM(QUANTITY) AS DECIMAL (10,2))/ CAST(COUNT(DISTINCT(ORDER_ID)) AS DECIMAL (10,2)) AS DECIMAL (10,2))  AS AVG_PIZZAS_PER_ORDER FROM pizza_sales

-- DAILY TRENDS 
SELECT DATENAME(DW,ORDER_DATE) AS ORDER_DAY , COUNT(DISTINCT(ORDER_ID)) AS TOTAL_ORDERS
FROM PIZZA_SALES
GROUP BY DATENAME(DW,ORDER_DATE)

-- HOURLY TRENDS 
SELECT DATEPART(HOUR, ORDER_TIME) AS ORDER_HOURS , COUNT(DISTINCT(ORDER_ID)) AS TOTAL_ORDERS
FROM pizza_sales
GROUP BY DATEPART(HOUR, ORDER_TIME)
ORDER BY DATEPART(HOUR, ORDER_TIME)

-- PERCENTAGE SALES BY PIZZA CATEGORY
SELECT PIZZA_CATEGORY,
CAST(SUM(TOTAL_PRICE) AS DECIMAL (10,2)) AS TOTAL_SALES,
CAST(SUM(TOTAL_PRICE)*100 / (SELECT SUM(TOTAL_PRICE) FROM pizza_sales) AS DECIMAL (10,2)) AS TOTAL_SALES
FROM pizza_sales
GROUP BY PIZZA_CATEGORY

-- PERCENTAGE SALES BY PIZZZA SIZE
SELECT pizza_size,
CAST(SUM(TOTAL_PRICE) AS DECIMAL (10,2)) AS TOTAL_SALES,
CAST(SUM(TOTAL_PRICE)*100 / (SELECT SUM(TOTAL_PRICE) FROM pizza_sales) AS DECIMAL (10,2)) AS TOTAL_SALES
FROM pizza_sales
GROUP BY pizza_size
ORDER BY pizza_size

--TOTAL PIZZAS SOLD BY PIZZA CATEGORY
SELECT PIZZA_CATEGORY,SUM(QUANTITY) AS TOTAL_PIZZAS_SOLD
FROM pizza_sales
GROUP BY PIZZA_CATEGORY

-- TOP5 BEST SELLERS BY TOTAL PIZZAS SOLD
SELECT TOP 5 (pizza_name) AS BEST_SELLER, SUM(QUANTITY) AS TOTAL_PIZZAS_SOLD
FROM pizza_sales
GROUP BY pizza_name
ORDER BY SUM(QUANTITY) DESC

--BOTTOM 5 WORST SELLERS BY TOTAL PIZZAS SOLD
SELECT TOP 5(pizza_name) AS WORST_SELLER, SUM(QUANTITY) AS TOTAL_PIZZAS_SOLD
FROM pizza_sales
GROUP BY pizza_name
ORDER BY SUM(QUANTITY)
